
-- =====================================
-- SCRIPT CORRIGIDO - CRIAÇÃO DE TABELAS
-- Sprint1BD - Projeto Mottu
-- =====================================

-- 1. FILIAL
CREATE TABLE FILIAL (
  ID_FILIAL NUMBER PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL,
  CIDADE VARCHAR2(100),
  ESTADO VARCHAR2(2)
);

-- 2. PATIO
CREATE TABLE PATIO (
  ID_PATIO NUMBER PRIMARY KEY,
  ID_FILIAL NUMBER,
  NOME_PATIO VARCHAR2(100),
  CAPACIDADE NUMBER,
  CONSTRAINT FK_PATIO_FILIAL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

-- 3. MODELOMOTO
CREATE TABLE MODELOMOTO (
  ID_MODELO NUMBER PRIMARY KEY,
  DESCRICAO VARCHAR2(100),
  TIPO_MOTOR VARCHAR2(50)
);

-- 4. MOTO
CREATE TABLE MOTO (
  ID_MOTO NUMBER PRIMARY KEY,
  PLACA VARCHAR2(10) UNIQUE NOT NULL,
  ID_MODELO NUMBER,
  ID_PATIO NUMBER,
  STATUS VARCHAR2(50),
  CONSTRAINT FK_MOTO_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELOMOTO(ID_MODELO),
  CONSTRAINT FK_MOTO_PATIO FOREIGN KEY (ID_PATIO) REFERENCES PATIO(ID_PATIO)
);

-- 5. CLIENTE
CREATE TABLE CLIENTE (
  ID_CLIENTE NUMBER PRIMARY KEY,
  NOME VARCHAR2(100),
  TELEFONE VARCHAR2(15),
  DOCUMENTO VARCHAR2(20)
);

-- 6. ALUGUEL
CREATE TABLE ALUGUEL (
  ID_ALUGUEL NUMBER PRIMARY KEY,
  ID_CLIENTE NUMBER,
  ID_MOTO NUMBER,
  DATA_INICIO DATE,
  DATA_FIM DATE,
  CONSTRAINT FK_ALUGUEL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  CONSTRAINT FK_ALUGUEL_MOTO FOREIGN KEY (ID_MOTO) REFERENCES MOTO(ID_MOTO)
);

-- 7. LOCALIZACAOMOTO
CREATE TABLE LOCALIZACAOMOTO (
  ID_LOCALIZACAO NUMBER PRIMARY KEY,
  ID_MOTO NUMBER,
  DATA_REGISTRO DATE,
  LATITUDE VARCHAR2(50),
  LONGITUDE VARCHAR2(50),
  CONSTRAINT FK_LOC_MOTO FOREIGN KEY (ID_MOTO) REFERENCES MOTO(ID_MOTO)
);

-- 8. MANUTENCAO
CREATE TABLE MANUTENCAO (
  ID_MANUTENCAO NUMBER PRIMARY KEY,
  ID_MOTO NUMBER,
  DATA_MANUTENCAO DATE,
  TIPO VARCHAR2(50),
  OBSERVACOES VARCHAR2(255),
  CONSTRAINT FK_MANUTENCAO_MOTO FOREIGN KEY (ID_MOTO) REFERENCES MOTO(ID_MOTO)
);

-- 9. SENSOR
CREATE TABLE SENSOR (
  ID_SENSOR NUMBER PRIMARY KEY,
  ID_MOTO NUMBER,
  TIPO_SENSOR VARCHAR2(50),
  STATUS VARCHAR2(50),
  CONSTRAINT FK_SENSOR_MOTO FOREIGN KEY (ID_MOTO) REFERENCES MOTO(ID_MOTO)
);
